
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE)
library(tidyverse)
```

# The R community

*Written by Annie Collins and last updated on 7 October 2021.*

## Introduction

Once you've gotten a basic handle on coding in R, there are plenty of ways to extend your learning and practice beyond the classroom. R has a global network of users of all levels and backgrounds, and these users have established a myriad of outlets for connecting with each other and sharing their R expertise, projects, and discoveries.

In this module, we will look at three resources for participating in the R community: **R Weekly**, **R-Ladies**, and **R Meetups**.

## R Weekly

> "R is growing very quickly, and there are lots of great blogs, tutorials and other formats of resources coming out every day. R Weekly wants to keep track of these great things in the R community and make it more accessible to everyone."

R Weekly is a (you guessed it) weekly summary of all things R related: educational resources, new packages, videos, podcasts, examples of real world R use, and much more. All features are compiled and posted each Monday on [RWeekly.org](https://rweekly.org/) as well as delivered in the form of an e-newsletter to email subscribers. R Weekly is a great resource for keeping up to date with developments in the broader R community, as well as share your own projects with a large audience of R users of all levels.

### Get involved

- Check out the current and past iterations of R Weekly on their [website](https://rweekly.org/).
- Subscribe to the R Weekly [mailing list](https://feedburner.google.com/fb/a/mailverify?uri=rweekly&loc=en_US).
- Follow R Weekly on their various social media accounts: [Facebook](https://facebook.com/rweekly) and [Twitter](https://twitter.com/rweekly_org).

## R-Ladies

> "R-Ladies is a worldwide organization whose mission is to promote gender diversity in the R community."

R-Ladies focuses on increasing the proportion of underrepresented genders in the global R community through encouraging, inspiring, and empowering minority gender (cis/trans women, trans men, nonbinary, etc.) R users. Their efforts involve creating a global network of R leaders and learners via local meet ups, a directory of individual speaker profiles, and community and network-focused online communication channels (Twitter, Slack, GitHub, etc.).

### Get involved

- Follow \@RLadiesGlobal on [Twitter](https://twitter.com/RLadiesGlobal).
- Find your [local R-Ladies chapter](https://www.meetup.com/pro/rladies/) and meet-ups ([R-Ladies Toronto](https://www.meetup.com/rladies-toronto/) is co-organized by the University of Toronto's own Monica Alexander!).
- Contribute to the R-Ladies Global [GitHub](https://github.com/rladies).
- Join the R-Ladies community [Slack channel](https://rladies-community-slack.herokuapp.com/).


## R meetups

Online or in-person meet ups are a great way to meet like-minded individuals, exchange knowledge and experience, and develop your R skills and network. As mentioned previously, there are R-Ladies-specific meet ups, as well as a worldwide network of R User Groups, both of which have been sponsored by the R Consortium.

### Get involved

- Join the [Greater Toronto Area (GTA) R User Group](https://www.meetup.com/Greater-Toronto-Area-GTA-R-Users-Group/)
 or [find your local R User Group](https://www.meetup.com/pro/r-user-groups)
