
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# (PART\*) Git outta here {-}
 
# Introduction

*Written by Rohan Alexander*

In this module, we are going to go through git and version control.

Git is a way of working with other people, even if that other person is just your future-self. It allows us to take snapshots of our work at certain times. We can then return to those snapshots, or combine those snapshots with other people.

GitHub is built on top of git and has become the main way that people interact with git, especially initially. This adds a website and a bunch of functionality around git that help us to use it.

The main thing to remember with git and GitHub is that you can't really break anything. It can intimidating to get started with it because it all seems so, well, 'hacker'. But you can do it.

The lessons in this module are:

- What is version control and GitHub?, written by Mariam Walaa.
- Git: pull, status, add, commit, push, written by Mariam Walaa.
- Branches in GitHub, written by Matthew Wankiewicz.
- Dealing with Conflicts, written by Matthew Wankiewicz.
- Putting (G)it All together in RStudio, written by Matthew Wankiewicz.
