
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
# library(learnr)
# tutorial_options(exercise.eval = FALSE)
library(flair)
# library(gradethis)
library(sortable)
# gradethis::gradethis_setup()
# library(palmerpenguins)
library(ggmap)
```



# (PART\*) Indistinguishable from magic {-}

# Introduction

*Written by Rohan Alexander.*

In this module, we are going to go through various aspects that are, and there's no word for this other than, magical. We learn R because we're forced to for a class or work, or because we have some problem that a 'friend' says we should solve in R. Eventually we get better at it, but it's a slog. But when you get to this module, we start to see the power of the foundation that we've established.

We will be able to make websites using R! We will be able to make interactive applications using R. After using countless packages throughout these modules, we'll even be able to write out own packages! There are also a few aspects around style that are worth addressing at this point, and so there is also a lesson on that. 

For me, it was when I got to this type of content, that I started to really 'get' R. And I hope that you feel similarly.


